server:
  port: ${PORT:8080}

spring:
  application:
    name: quiz
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/quizisso?characterEncoding=UTF-8&useUnicode=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:s0f0d@o69420}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET NAMES 'UTF8'"
  
  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
